version: '2'

services:
  nginx:
    image: nginxproxy/nginx-proxy:0.10-alpine
    restart: unless-stopped
    ports:
      - 80:80
    networks:
      - nginx-proxy
    volumes:
      - /etc/localtime/:/etc/localtime:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro

networks:
  nginx-proxy:
    name: nginx-proxy
