version: '3.5'

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy:0.10-alpine
    restart: unless-stopped
    ports:
      - 80:80
    networks:
      - nginx-proxy
    volumes:
      - /etc/localtime/:/etc/localtime:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./conf.d:/etc/nginx/conf.d:ro
      - ./vhost.d:/etc/nginx/vhost.d:ro

networks:
  nginx-proxy:
    name: nginx-proxy
