version: '3.5'

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy:0.10-alpine
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    networks:
      - nginx-proxy
    volumes:
      - /etc/localtime/:/etc/localtime:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - ./conf.d:/etc/nginx/conf.d
      - ./vhost.d:/etc/nginx/vhost.d
  nginx-proxy-acme:
    image: nginxproxy/acme-companion:2.1
    container_name: nginx-proxy-acme
    restart: unless-stopped
    environment:
      DEFAULT_EMAIL: ${DEFAULT_EMAIL}
      NGINX_PROXY_CONTAINER: nginx-proxy
    volumes:
      - /etc/localtime/:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - acme:/etc/acme.sh
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - ./vhost.d:/etc/nginx/vhost.d
volumes:
  certs:
  acme:
  html:

networks:
  nginx-proxy:
    name: nginx-proxy
